version: "3.1"

networks:
  fyp-network:
    external: true

services:
  node1:
    image: fyp
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      NODE_ID: 0
  node2:
    image: fyp
    ports:
      - "81:80"
      - "8001:8001"
    environment:
      NODE_ID: 1
  node3:
    image: fyp
    ports:
      - "82:80"
      - "8002:8002"
    environment:
      NODE_ID: 2
  node4:
    image: fyp
    ports:
      - "83:80"
      - "8003:8003"
    environment:
      NODE_ID: 3
  node5:
    image: fyp
    ports:
      - "84:80"
      - "8004:8004"
    environment:
      NODE_ID: 4